<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-02 15:25:46                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class AttachmentImagesDAO extends OneToManyLinked
	{
		public function __construct(Attachment $attachment, $lazy = false)
		{
			parent::__construct(
				$attachment,
				AttachmentImage::dao(),
				$lazy
			);
		}
		
		/**
		 * @return AttachmentImagesDAO
		**/
		public static function create(Attachment $attachment, $lazy = false)
		{
			return new self($attachment, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'attachment_id';
		}
	}
?>