<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-05-03 16:07:07                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class BoardStatsDailyDAO extends AutoBoardStatsDailyDAO
	{
        public function getPeriodFieldName()
        {
            return 'date';
        }

        public function getPeriodDateTruncArg()
        {
            return 'day';
        }

        public function truncateTimestamp(Timestamp $timestamp)
        {
            return Timestamp::create($timestamp->toFormatString('Y-m-d 00:00:00'));
        }


    }
?>