<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-08-21 13:30:17                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class BoardThreadsDAO extends OneToManyLinked
	{
		public function __construct(Board $board, $lazy = false)
		{
			parent::__construct(
				$board,
				Thread::dao(),
				$lazy
			);
		}
		
		/**
		 * @return BoardThreadsDAO
		**/
		public static function create(Board $board, $lazy = false)
		{
			return new self($board, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'board_id';
		}
	}
?>