<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-05-02 20:12:17                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class BoardStatsHourlyDAO extends AutoBoardStatsHourlyDAO
	{

        public function getPeriodFieldName()
        {
            return 'hour';
        }

        public function getPeriodDateTruncArg()
        {
            return 'hour';
        }

        public function truncateTimestamp(Timestamp $timestamp)
        {
            return Timestamp::create($timestamp->toFormatString('Y-m-d H:00:00'));
        }


    }
?>