<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-04-07 17:00:39                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class DialogDAO extends AutoDialogDAO
	{

        /**
         * @param UserIdentity $as
         * @param UserIdentity $with
         * @return Dialog|null
         */
        public function get(UserIdentity $as, UserIdentity $with)
        {
            return Criteria::create(Dialog::dao())
                ->add(Expression::eq('as', $as))
                ->add(Expression::eq('with', $with))
                ->get();
        }
	}
?>