<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-07 19:01:27                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class DialogMessagesDAO extends ManyToManyLinked
	{
		public function __construct(Dialog $dialog, $lazy = false)
		{
			parent::__construct(
				$dialog,
				DialogMessage::dao(),
				$lazy
			);
		}
		
		/**
		 * @return DialogMessagesDAO
		**/
		public static function create(Dialog $dialog, $lazy = false)
		{
			return new self($dialog, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'dialog_message_dialog';
		}
		
		public function getChildIdField()
		{
			return 'dialog_message_id';
		}
		
		public function getParentIdField()
		{
			return 'dialog_id';
		}
	}
?>