<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-04-18 23:11:47                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModeratorLogDAO extends AutoModeratorLogDAO
	{
        private $selectHead = null;

        public function makeSelectHead()
        {
            if (!$this->selectHead) {
                $table = $this->getTable();

                $fields = [];
                foreach (ModeratorLogEventType::getClassMap() as $className) {
                    /** @var $className ModeratorLog */
                    $dao = $className::dao();
                    $fields = array_merge($fields, $dao->getFields());
                }

                $this->selectHead = OSQL::select()->from($table);
                foreach (array_unique($fields) as $field) {
                    $this->selectHead->get(new DBField($field, $table));
                }
            }

            return clone $this->selectHead;
        }

    }
?>