<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-24 14:37:17                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class PostReferencedBysDAO extends OneToManyLinked
	{
		public function __construct(Post $post, $lazy = false)
		{
			parent::__construct(
				$post,
				PostReference::dao(),
				$lazy
			);
		}
		
		/**
		 * @return PostReferencedBysDAO
		**/
		public static function create(Post $post, $lazy = false)
		{
			return new self($post, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'references_to_id';
		}
	}
?>