<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-02 15:25:46                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class PostAttachmentsDAO extends OneToManyLinked
	{
		public function __construct(Post $post, $lazy = false)
		{
			parent::__construct(
				$post,
				Attachment::dao(),
				$lazy
			);
		}
		
		/**
		 * @return PostAttachmentsDAO
		**/
		public static function create(Post $post, $lazy = false)
		{
			return new self($post, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'post_id';
		}
	}
?>