<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-02-18 16:39:29                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class PostReportsDAO extends OneToManyLinked
	{
		public function __construct(Post $post, $lazy = false)
		{
			parent::__construct(
				$post,
				PostReport::dao(),
				$lazy
			);
		}
		
		/**
		 * @return PostReportsDAO
		**/
		public static function create(Post $post, $lazy = false)
		{
			return new self($post, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'post_id';
		}
	}
?>