<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-24 14:37:17                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PostReferenceDAO extends AutoPostReferenceDAO
	{
		// your brilliant stuff goes here
	}
?>