<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-04-16 15:41:40                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class ThreadPostsDAO extends OneToManyLinked
	{
		public function __construct(Thread $thread, $lazy = false)
		{
			parent::__construct(
				$thread,
				Post::dao(),
				$lazy
			);
		}
		
		/**
		 * @return ThreadPostsDAO
		**/
		public static function create(Thread $thread, $lazy = false)
		{
			return new self($thread, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'thread_id';
		}
	}
?>