<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-08-21 18:20:57                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class UserFavouriteBoardsDAO extends OneToManyLinked
	{
		public function __construct(User $user, $lazy = false)
		{
			parent::__construct(
				$user,
				FavouriteBoard::dao(),
				$lazy
			);
		}
		
		/**
		 * @return UserFavouriteBoardsDAO
		**/
		public static function create(User $user, $lazy = false)
		{
			return new self($user, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'user_id';
		}
	}
?>