<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-07-04 19:30:08                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class UserWatchedThreadsDAO extends ManyToManyLinked
	{
		public function __construct(User $user, $lazy = false)
		{
			parent::__construct(
				$user,
				Thread::dao(),
				$lazy
			);
		}
		
		/**
		 * @return UserWatchedThreadsDAO
		**/
		public static function create(User $user, $lazy = false)
		{
			return new self($user, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'user_thread';
		}
		
		public function getChildIdField()
		{
			return 'thread_id';
		}
		
		public function getParentIdField()
		{
			return 'user_id';
		}

        public function makeQuery() {
            /** @var UnifiedContainerWorker $worker */
            $worker = $this->worker;
            return $worker->makeFetchQuery();
        }
	}
?>