<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-07 19:01:27                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class UserIdentityDialogsDAO extends OneToManyLinked
	{
		public function __construct(UserIdentity $userIdentity, $lazy = false)
		{
			parent::__construct(
				$userIdentity,
				Dialog::dao(),
				$lazy
			);
		}
		
		/**
		 * @return UserIdentityDialogsDAO
		**/
		public static function create(UserIdentity $userIdentity, $lazy = false)
		{
			return new self($userIdentity, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'as_id';
		}
	}
?>