<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-22 19:24:29                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class UserIdentityDAO extends AutoUserIdentityDAO implements IdentifiableByRequestDAO
	{
        /**
         * @param $address
         * @return UserIdentity
         * @throws ObjectNotFoundException
         */
        public function getByAddress($address) {
            if ($address === '' || $address === null) {
                throw new ObjectNotFoundException;
            }
            return $this->getByLogic(
                Expression::eq('address', $address)
            );
        }

        /** @return UserIdentity */
        public function getByRequestedValue($value) {
            return $this->getByAddress($value);
        }

    }
?>