<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-07 19:01:26                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoDialog extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Dialog', 8, true, true, false, null, null),
				'as' => LightMetaProperty::fill(new LightMetaProperty(), 'as', 'as_id', 'identifier', 'UserIdentity', null, true, false, false, 1, 3),
				'with' => LightMetaProperty::fill(new LightMetaProperty(), 'with', 'with_id', 'identifier', 'UserIdentity', null, true, false, false, 1, 3),
				'createdAt' => LightMetaProperty::fill(new LightMetaProperty(), 'createdAt', 'created_at', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'updatedAt' => LightMetaProperty::fill(new LightMetaProperty(), 'updatedAt', 'updated_at', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'messages' => LightMetaProperty::fill(new LightMetaProperty(), 'messages', 'dialog_message_id', 'identifierList', 'DialogMessage', null, false, false, false, 3, null)
			);
		}
	}
?>