<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-02-08 15:37:15                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoFavouriteBoard extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'FavouriteBoard', 8, true, true, false, null, null),
				'createDate' => LightMetaProperty::fill(new LightMetaProperty(), 'createDate', 'create_date', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'identifier', 'User', null, true, false, false, 1, 3),
				'board' => LightMetaProperty::fill(new LightMetaProperty(), 'board', 'board_id', 'identifier', 'Board', null, true, false, false, 1, 3)
			);
		}
	}
?>