<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-04-07 00:43:15                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoThread extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Thread', 8, true, true, false, null, null),
				'board' => LightMetaProperty::fill(new LightMetaProperty(), 'board', 'board_id', 'identifier', 'Board', null, true, false, false, 1, 3),
				'createDate' => LightMetaProperty::fill(new LightMetaProperty(), 'createDate', 'create_date', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'updateDate' => LightMetaProperty::fill(new LightMetaProperty(), 'updateDate', 'update_date', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'purgedAt' => LightMetaProperty::fill(new LightMetaProperty(), 'purgedAt', 'purged_at', 'timestamp', 'Timestamp', null, false, true, false, null, null),
				'deleted' => LightMetaProperty::fill(new LightMetaProperty(), 'deleted', null, 'boolean', null, null, true, true, false, null, null),
				'deletedAt' => LightMetaProperty::fill(new LightMetaProperty(), 'deletedAt', 'deleted_at', 'timestamp', 'Timestamp', null, false, true, false, null, null),
				'sticky' => LightMetaProperty::fill(new LightMetaProperty(), 'sticky', null, 'boolean', null, null, true, true, false, null, null),
				'locked' => LightMetaProperty::fill(new LightMetaProperty(), 'locked', null, 'boolean', null, null, true, true, false, null, null),
				'bumpLimitReached' => LightMetaProperty::fill(new LightMetaProperty(), 'bumpLimitReached', 'bump_limit_reached', 'boolean', null, null, true, true, false, null, null),
				'popularity' => LightMetaProperty::fill(new LightMetaProperty(), 'popularity', null, 'integer', null, 4, false, true, false, null, null),
				'posts' => LightMetaProperty::fill(new LightMetaProperty(), 'posts', 'posts_id', 'identifierList', 'Post', null, false, false, false, 2, null)
			);
		}
	}
?>