<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-04-02 14:29:15                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPost extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Post', 8, true, true, false, null, null),
				'thread' => LightMetaProperty::fill(new LightMetaProperty(), 'thread', 'thread_id', 'identifier', 'Thread', null, true, false, false, 1, 3),
				'parent' => LightMetaProperty::fill(new LightMetaProperty(), 'parent', 'parent_id', 'identifier', 'Post', null, false, false, false, 1, 3),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'identifier', 'User', null, false, false, false, 1, 3),
				'ipHash' => LightMetaProperty::fill(new LightMetaProperty(), 'ipHash', 'ip_hash', 'string', null, 64, false, true, false, null, null),
				'createDate' => LightMetaProperty::fill(new LightMetaProperty(), 'createDate', 'create_date', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'deleted' => LightMetaProperty::fill(new LightMetaProperty(), 'deleted', null, 'boolean', null, null, true, true, false, null, null),
				'message' => LightMetaProperty::fill(new LightMetaProperty(), 'message', null, 'string', null, 9001, false, true, false, null, null),
				'approved' => LightMetaProperty::fill(new LightMetaProperty(), 'approved', null, 'boolean', null, null, true, true, false, null, null),
				'banned' => LightMetaProperty::fill(new LightMetaProperty(), 'banned', null, 'boolean', null, null, true, true, false, null, null),
				'reports' => LightMetaProperty::fill(new LightMetaProperty(), 'reports', 'reports_id', 'identifierList', 'PostReport', null, false, false, false, 2, null),
				'replies' => LightMetaProperty::fill(new LightMetaProperty(), 'replies', 'replies_id', 'identifierList', 'Post', null, false, false, false, 2, null),
				'attachments' => LightMetaProperty::fill(new LightMetaProperty(), 'attachments', 'attachments_id', 'identifierList', 'Attachment', null, false, false, false, 2, null),
				'referencedBys' => LightMetaProperty::fill(new LightMetaProperty(), 'referencedBys', 'referenced_bys_id', 'identifierList', 'PostReference', null, false, false, false, 2, null),
				'referencesTos' => LightMetaProperty::fill(new LightMetaProperty(), 'referencesTos', 'references_tos_id', 'identifierList', 'PostReference', null, false, false, false, 2, null)
			);
		}
	}
?>