<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-05-02 20:12:17                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoBoardStatsHourly extends ProtoBoardStats
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'BoardStatsHourly', 8, true, true, false, null, null),
						'hour' => LightMetaProperty::fill(new LightMetaProperty(), 'hour', null, 'timestamp', 'Timestamp', null, true, true, false, null, null)
					)
				);
		}
	}
?>