<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-02-08 15:37:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoVideo extends ProtoAttachment
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'service' => LightMetaProperty::fill(new LightMetaProperty(), 'service', 'service_id', 'enum', 'VideoService', null, true, false, false, 1, 3),
						'videoId' => LightMetaProperty::fill(new LightMetaProperty(), 'videoId', 'video_id', 'string', null, 64, true, true, false, null, null),
						'previewUrl' => LightMetaProperty::fill(new LightMetaProperty(), 'previewUrl', 'preview_url', 'string', null, 255, true, true, false, null, null),
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Video', 8, true, true, false, null, null)
					)
				);
		}
	}
?>