<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-23 00:54:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoAttachmentImage extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'AttachmentImage', 8, true, true, false, null, null),
				'role' => LightMetaProperty::fill(new LightMetaProperty(), 'role', 'role_id', 'enum', 'AttachmentImageRole', null, false, false, false, 1, 3),
				'attachment' => LightMetaProperty::fill(new LightMetaProperty(), 'attachment', 'attachment_id', 'identifier', 'Attachment', null, true, false, false, 1, 3),
				'server' => LightMetaProperty::fill(new LightMetaProperty(), 'server', null, 'string', null, 64, false, true, false, null, null),
				'filename' => LightMetaProperty::fill(new LightMetaProperty(), 'filename', null, 'string', null, 64, true, true, false, null, null),
				'fileSize' => LightMetaProperty::fill(new LightMetaProperty(), 'fileSize', 'file_size', 'integer', null, 4, true, true, false, null, null),
				'width' => LightMetaProperty::fill(new LightMetaProperty(), 'width', null, 'integer', null, 4, true, true, false, null, null),
				'height' => LightMetaProperty::fill(new LightMetaProperty(), 'height', null, 'integer', null, 4, true, true, false, null, null)
			);
		}
	}
?>