<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-03 21:00:45                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoAttachmentEmbed extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'AttachmentEmbed', 8, true, true, false, null, null),
				'service' => LightMetaProperty::fill(new LightMetaProperty(), 'service', 'service_id', 'enum', 'AttachmentEmbedService', null, true, false, false, 1, 3),
				'embedId' => LightMetaProperty::fill(new LightMetaProperty(), 'embedId', 'embed_id', 'string', null, 255, true, true, false, null, null),
				'title' => LightMetaProperty::fill(new LightMetaProperty(), 'title', null, 'string', null, 255, false, true, false, null, null)
			);
		}
	}
?>