<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-04-07 00:32:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoBoard extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Board', 8, true, true, false, null, null),
				'dir' => LightMetaProperty::fill(new LightMetaProperty(), 'dir', null, 'string', null, 16, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 255, true, true, false, null, null),
				'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, null, false, true, false, null, null),
				'hidden' => LightMetaProperty::fill(new LightMetaProperty(), 'hidden', null, 'boolean', null, null, true, true, false, null, null),
				'nsfw' => LightMetaProperty::fill(new LightMetaProperty(), 'nsfw', null, 'boolean', null, null, true, true, false, null, null),
				'blockRu' => LightMetaProperty::fill(new LightMetaProperty(), 'blockRu', 'block_ru', 'boolean', null, null, true, true, false, null, null),
				'createDate' => LightMetaProperty::fill(new LightMetaProperty(), 'createDate', 'create_date', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'owner' => LightMetaProperty::fill(new LightMetaProperty(), 'owner', 'owner_id', 'identifier', 'User', null, true, false, false, 1, 3),
				'deleted' => LightMetaProperty::fill(new LightMetaProperty(), 'deleted', null, 'boolean', null, null, true, true, false, null, null),
				'deletedAt' => LightMetaProperty::fill(new LightMetaProperty(), 'deletedAt', 'deleted_at', 'timestamp', 'Timestamp', null, false, true, false, null, null),
				'popularity' => LightMetaProperty::fill(new LightMetaProperty(), 'popularity', null, 'integer', null, 4, false, true, false, null, null),
				'bumpLimit' => LightMetaProperty::fill(new LightMetaProperty(), 'bumpLimit', 'bump_limit', 'integer', null, 4, true, true, false, null, null),
				'threadLimit' => LightMetaProperty::fill(new LightMetaProperty(), 'threadLimit', 'thread_limit', 'integer', null, 4, true, true, false, null, null),
				'favouritedBy' => LightMetaProperty::fill(new LightMetaProperty(), 'favouritedBy', 'favourited_by_id', 'identifierList', 'FavouriteBoard', null, false, false, false, 2, null),
				'moderators' => LightMetaProperty::fill(new LightMetaProperty(), 'moderators', 'moderators_id', 'identifierList', 'BoardModerator', null, false, false, false, 2, null),
				'threads' => LightMetaProperty::fill(new LightMetaProperty(), 'threads', 'threads_id', 'identifierList', 'Thread', null, false, false, false, 2, null)
			);
		}
	}
?>