<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2018-01-04 16:10:53                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoAttachment extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Attachment', 8, true, true, false, null, null),
				'createDate' => LightMetaProperty::fill(new LightMetaProperty(), 'createDate', 'create_date', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'post' => LightMetaProperty::fill(new LightMetaProperty(), 'post', 'post_id', 'identifier', 'Post', null, false, false, false, 1, 3),
				'publishToken' => LightMetaProperty::fill(new LightMetaProperty(), 'publishToken', 'publish_token', 'string', null, 32, true, true, false, null, null),
				'published' => LightMetaProperty::fill(new LightMetaProperty(), 'published', null, 'boolean', null, null, true, true, false, null, null),
				'deleted' => LightMetaProperty::fill(new LightMetaProperty(), 'deleted', null, 'boolean', null, null, true, true, false, null, null),
				'deletedAt' => LightMetaProperty::fill(new LightMetaProperty(), 'deletedAt', 'deleted_at', 'timestamp', 'Timestamp', null, false, true, false, null, null),
				'nsfw' => LightMetaProperty::fill(new LightMetaProperty(), 'nsfw', null, 'boolean', null, null, false, true, false, null, null),
				'embed' => LightMetaProperty::fill(new LightMetaProperty(), 'embed', 'embed_id', 'identifier', 'AttachmentEmbed', null, false, false, false, 1, 3),
				'images' => LightMetaProperty::fill(new LightMetaProperty(), 'images', 'images_id', 'identifierList', 'AttachmentImage', null, false, false, false, 2, null)
			);
		}
	}
?>