<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-02-08 15:37:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoUserSession extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'sessionId' => LightMetaProperty::fill(new LightMetaProperty(), 'sessionId', 'session_id', 'string', null, null, true, true, false, null, null),
				'userId' => LightMetaProperty::fill(new LightMetaProperty(), 'userId', 'user_id', 'integer', null, 8, false, true, false, null, null),
				'ipAddress' => LightMetaProperty::fill(new LightMetaProperty(), 'ipAddress', 'ip_address', 'string', null, null, false, true, false, null, null),
				'userAgent' => LightMetaProperty::fill(new LightMetaProperty(), 'userAgent', 'user_agent', 'string', null, null, false, true, false, null, null)
			);
		}
	}
?>