<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-24 14:37:17                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPostReference extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PostReference', 8, true, true, false, null, null),
				'referencedBy' => LightMetaProperty::fill(new LightMetaProperty(), 'referencedBy', 'referenced_by_id', 'identifier', 'Post', null, true, false, false, 1, 3),
				'referencesTo' => LightMetaProperty::fill(new LightMetaProperty(), 'referencesTo', 'references_to_id', 'identifier', 'Post', null, true, false, false, 1, 3)
			);
		}
	}
?>