<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-04-09 21:59:50                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPostReport extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PostReport', 8, true, true, false, null, null),
				'post' => LightMetaProperty::fill(new LightMetaProperty(), 'post', 'post_id', 'identifier', 'Post', null, true, false, false, 1, 3),
				'date' => LightMetaProperty::fill(new LightMetaProperty(), 'date', null, 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'reason' => LightMetaProperty::fill(new LightMetaProperty(), 'reason', null, 'string', null, 1000, true, true, false, null, null),
				'reportedBy' => LightMetaProperty::fill(new LightMetaProperty(), 'reportedBy', 'reported_by_id', 'identifier', 'User', null, false, false, false, 1, 3),
				'reportedByIpHash' => LightMetaProperty::fill(new LightMetaProperty(), 'reportedByIpHash', 'reported_by_ip_hash', 'string', null, 64, false, true, false, null, null)
			);
		}
	}
?>