<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-23 01:07:32                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoStorageTrash extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'StorageTrash', 8, true, true, false, null, null),
				'server' => LightMetaProperty::fill(new LightMetaProperty(), 'server', null, 'string', null, 64, true, true, false, null, null),
				'filename' => LightMetaProperty::fill(new LightMetaProperty(), 'filename', null, 'string', null, 64, true, true, false, null, null)
			);
		}
	}
?>