<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-02-08 15:37:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoUserSession
	{
		protected $sessionId = null;
		protected $userId = null;
		protected $ipAddress = null;
		protected $userAgent = null;
		
		public function getSessionId()
		{
			return $this->sessionId;
		}
		
		/**
		 * @return UserSession
		**/
		public function setSessionId($sessionId)
		{
			$this->sessionId = $sessionId;
			
			return $this;
		}
		
		public function getUserId()
		{
			return $this->userId;
		}
		
		/**
		 * @return UserSession
		**/
		public function setUserId($userId)
		{
			$this->userId = $userId;
			
			return $this;
		}
		
		public function getIpAddress()
		{
			return $this->ipAddress;
		}
		
		/**
		 * @return UserSession
		**/
		public function setIpAddress($ipAddress)
		{
			$this->ipAddress = $ipAddress;
			
			return $this;
		}
		
		public function getUserAgent()
		{
			return $this->userAgent;
		}
		
		/**
		 * @return UserSession
		**/
		public function setUserAgent($userAgent)
		{
			$this->userAgent = $userAgent;
			
			return $this;
		}
	}
?>