<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-02-08 15:37:15                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFavouriteBoard extends IdentifiableObject
	{
		protected $createDate = null;
		protected $user = null;
		protected $userId = null;
		protected $board = null;
		protected $boardId = null;
		
		/**
		 * @return Timestamp
		**/
		public function getCreateDate()
		{
			return $this->createDate;
		}
		
		/**
		 * @return FavouriteBoard
		**/
		public function setCreateDate(Timestamp $createDate)
		{
			$this->createDate = $createDate;
			
			return $this;
		}
		
		/**
		 * @return FavouriteBoard
		**/
		public function dropCreateDate()
		{
			$this->createDate = null;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function getUser()
		{
			if (!$this->user && $this->userId) {
				$this->user = User::dao()->getById($this->userId);
			}
			
			return $this->user;
		}
		
		public function getUserId()
		{
			return $this->user
				? $this->user->getId()
				: $this->userId;
		}
		
		/**
		 * @return FavouriteBoard
		**/
		public function setUser(User $user)
		{
			$this->user = $user;
			$this->userId = $user ? $user->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return FavouriteBoard
		**/
		public function setUserId($id)
		{
			$this->user = null;
			$this->userId = $id;
			
			return $this;
		}
		
		/**
		 * @return FavouriteBoard
		**/
		public function dropUser()
		{
			$this->user = null;
			$this->userId = null;
			
			return $this;
		}
		
		/**
		 * @return Board
		**/
		public function getBoard()
		{
			if (!$this->board && $this->boardId) {
				$this->board = Board::dao()->getById($this->boardId);
			}
			
			return $this->board;
		}
		
		public function getBoardId()
		{
			return $this->board
				? $this->board->getId()
				: $this->boardId;
		}
		
		/**
		 * @return FavouriteBoard
		**/
		public function setBoard(Board $board)
		{
			$this->board = $board;
			$this->boardId = $board ? $board->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return FavouriteBoard
		**/
		public function setBoardId($id)
		{
			$this->board = null;
			$this->boardId = $id;
			
			return $this;
		}
		
		/**
		 * @return FavouriteBoard
		**/
		public function dropBoard()
		{
			$this->board = null;
			$this->boardId = null;
			
			return $this;
		}
	}
?>