<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-03 21:00:45                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAttachmentEmbed extends IdentifiableObject
	{
		protected $service = null;
		protected $serviceId = null;
		protected $embedId = null;
		protected $title = null;
		
		/**
		 * @return AttachmentEmbedService
		**/
		public function getService()
		{
			if (!$this->service && $this->serviceId) {
				$this->service = new AttachmentEmbedService($this->serviceId);
			}
			
			return $this->service;
		}
		
		public function getServiceId()
		{
			return $this->service
				? $this->service->getId()
				: $this->serviceId;
		}
		
		/**
		 * @return AttachmentEmbed
		**/
		public function setService(AttachmentEmbedService $service)
		{
			$this->service = $service;
			$this->serviceId = $service ? $service->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return AttachmentEmbed
		**/
		public function setServiceId($id)
		{
			$this->service = null;
			$this->serviceId = $id;
			
			return $this;
		}
		
		/**
		 * @return AttachmentEmbed
		**/
		public function dropService()
		{
			$this->service = null;
			$this->serviceId = null;
			
			return $this;
		}
		
		public function getEmbedId()
		{
			return $this->embedId;
		}
		
		/**
		 * @return AttachmentEmbed
		**/
		public function setEmbedId($embedId)
		{
			$this->embedId = $embedId;
			
			return $this;
		}
		
		public function getTitle()
		{
			return $this->title;
		}
		
		/**
		 * @return AttachmentEmbed
		**/
		public function setTitle($title)
		{
			$this->title = $title;
			
			return $this;
		}
	}
?>