<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2018-01-04 15:17:04                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModeratorLog_Attachment extends ModeratorLog_Post
	{
		protected $attachmentId = null;
		
		public function getAttachmentId()
		{
			return $this->attachmentId;
		}
		
		/**
		 * @return ModeratorLog_Attachment
		**/
		public function setAttachmentId($attachmentId)
		{
			$this->attachmentId = $attachmentId;
			
			return $this;
		}
	}
?>