<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-02-13 14:12:45                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoBoardModerator extends IdentifiableObject
	{
		protected $createdAt = null;
		protected $user = null;
		protected $userId = null;
		protected $board = null;
		protected $boardId = null;
		protected $initiator = null;
		protected $initiatorId = null;
		
		/**
		 * @return Timestamp
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return BoardModerator
		**/
		public function setCreatedAt(Timestamp $createdAt)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return BoardModerator
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function getUser()
		{
			if (!$this->user && $this->userId) {
				$this->user = User::dao()->getById($this->userId);
			}
			
			return $this->user;
		}
		
		public function getUserId()
		{
			return $this->user
				? $this->user->getId()
				: $this->userId;
		}
		
		/**
		 * @return BoardModerator
		**/
		public function setUser(User $user)
		{
			$this->user = $user;
			$this->userId = $user ? $user->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return BoardModerator
		**/
		public function setUserId($id)
		{
			$this->user = null;
			$this->userId = $id;
			
			return $this;
		}
		
		/**
		 * @return BoardModerator
		**/
		public function dropUser()
		{
			$this->user = null;
			$this->userId = null;
			
			return $this;
		}
		
		/**
		 * @return Board
		**/
		public function getBoard()
		{
			if (!$this->board && $this->boardId) {
				$this->board = Board::dao()->getById($this->boardId);
			}
			
			return $this->board;
		}
		
		public function getBoardId()
		{
			return $this->board
				? $this->board->getId()
				: $this->boardId;
		}
		
		/**
		 * @return BoardModerator
		**/
		public function setBoard(Board $board)
		{
			$this->board = $board;
			$this->boardId = $board ? $board->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return BoardModerator
		**/
		public function setBoardId($id)
		{
			$this->board = null;
			$this->boardId = $id;
			
			return $this;
		}
		
		/**
		 * @return BoardModerator
		**/
		public function dropBoard()
		{
			$this->board = null;
			$this->boardId = null;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function getInitiator()
		{
			if (!$this->initiator && $this->initiatorId) {
				$this->initiator = User::dao()->getById($this->initiatorId);
			}
			
			return $this->initiator;
		}
		
		public function getInitiatorId()
		{
			return $this->initiator
				? $this->initiator->getId()
				: $this->initiatorId;
		}
		
		/**
		 * @return BoardModerator
		**/
		public function setInitiator(User $initiator)
		{
			$this->initiator = $initiator;
			$this->initiatorId = $initiator ? $initiator->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return BoardModerator
		**/
		public function setInitiatorId($id)
		{
			$this->initiator = null;
			$this->initiatorId = $id;
			
			return $this;
		}
		
		/**
		 * @return BoardModerator
		**/
		public function dropInitiator()
		{
			$this->initiator = null;
			$this->initiatorId = null;
			
			return $this;
		}
	}
?>