<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-07 19:01:26                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoDialog extends IdentifiableObject
	{
		protected $as = null;
		protected $asId = null;
		protected $with = null;
		protected $withId = null;
		protected $createdAt = null;
		protected $updatedAt = null;
		protected $messages = null;
		
		/**
		 * @return UserIdentity
		**/
		public function getAs()
		{
			if (!$this->as && $this->asId) {
				$this->as = UserIdentity::dao()->getById($this->asId);
			}
			
			return $this->as;
		}
		
		public function getAsId()
		{
			return $this->as
				? $this->as->getId()
				: $this->asId;
		}
		
		/**
		 * @return Dialog
		**/
		public function setAs(UserIdentity $as)
		{
			$this->as = $as;
			$this->asId = $as ? $as->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return Dialog
		**/
		public function setAsId($id)
		{
			$this->as = null;
			$this->asId = $id;
			
			return $this;
		}
		
		/**
		 * @return Dialog
		**/
		public function dropAs()
		{
			$this->as = null;
			$this->asId = null;
			
			return $this;
		}
		
		/**
		 * @return UserIdentity
		**/
		public function getWith()
		{
			if (!$this->with && $this->withId) {
				$this->with = UserIdentity::dao()->getById($this->withId);
			}
			
			return $this->with;
		}
		
		public function getWithId()
		{
			return $this->with
				? $this->with->getId()
				: $this->withId;
		}
		
		/**
		 * @return Dialog
		**/
		public function setWith(UserIdentity $with)
		{
			$this->with = $with;
			$this->withId = $with ? $with->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return Dialog
		**/
		public function setWithId($id)
		{
			$this->with = null;
			$this->withId = $id;
			
			return $this;
		}
		
		/**
		 * @return Dialog
		**/
		public function dropWith()
		{
			$this->with = null;
			$this->withId = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return Dialog
		**/
		public function setCreatedAt(Timestamp $createdAt)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return Dialog
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getUpdatedAt()
		{
			return $this->updatedAt;
		}
		
		/**
		 * @return Dialog
		**/
		public function setUpdatedAt(Timestamp $updatedAt)
		{
			$this->updatedAt = $updatedAt;
			
			return $this;
		}
		
		/**
		 * @return Dialog
		**/
		public function dropUpdatedAt()
		{
			$this->updatedAt = null;
			
			return $this;
		}
		
		/**
		 * @return DialogMessagesDAO
		**/
		public function getMessages($lazy = false)
		{
			if (!$this->messages || ($this->messages->isLazy() != $lazy)) {
				$this->messages = new DialogMessagesDAO($this, $lazy);
			}
			
			return $this->messages;
		}
		
		/**
		 * @return Dialog
		**/
		public function fillMessages($collection, $lazy = false)
		{
			$this->messages = new DialogMessagesDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->messages->mergeList($collection);
			
			return $this;
		}
	}
?>