<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-29 19:01:34                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModeratorLog_Post extends ModeratorLog
	{
		protected $threadId = null;
		protected $threadTitle = null;
		protected $postId = null;
		
		public function getThreadId()
		{
			return $this->threadId;
		}
		
		/**
		 * @return ModeratorLog_Post
		**/
		public function setThreadId($threadId)
		{
			$this->threadId = $threadId;
			
			return $this;
		}
		
		public function getThreadTitle()
		{
			return $this->threadTitle;
		}
		
		/**
		 * @return ModeratorLog_Post
		**/
		public function setThreadTitle($threadTitle)
		{
			$this->threadTitle = $threadTitle;
			
			return $this;
		}
		
		public function getPostId()
		{
			return $this->postId;
		}
		
		/**
		 * @return ModeratorLog_Post
		**/
		public function setPostId($postId)
		{
			$this->postId = $postId;
			
			return $this;
		}
	}
?>