<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-23 00:53:36                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAttachmentImage extends IdentifiableObject
	{
		protected $role = null;
		protected $roleId = null;
		protected $attachment = null;
		protected $attachmentId = null;
		protected $server = null;
		protected $filename = null;
		protected $fileSize = null;
		protected $width = null;
		protected $height = null;
		
		/**
		 * @return AttachmentImageRole
		**/
		public function getRole()
		{
			if (!$this->role && $this->roleId) {
				$this->role = new AttachmentImageRole($this->roleId);
			}
			
			return $this->role;
		}
		
		public function getRoleId()
		{
			return $this->role
				? $this->role->getId()
				: $this->roleId;
		}
		
		/**
		 * @return AttachmentImage
		**/
		public function setRole(AttachmentImageRole $role = null)
		{
			$this->role = $role;
			$this->roleId = $role ? $role->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return AttachmentImage
		**/
		public function setRoleId($id = null)
		{
			$this->role = null;
			$this->roleId = $id;
			
			return $this;
		}
		
		/**
		 * @return AttachmentImage
		**/
		public function dropRole()
		{
			$this->role = null;
			$this->roleId = null;
			
			return $this;
		}
		
		/**
		 * @return Attachment
		**/
		public function getAttachment()
		{
			if (!$this->attachment && $this->attachmentId) {
				$this->attachment = Attachment::dao()->getById($this->attachmentId);
			}
			
			return $this->attachment;
		}
		
		public function getAttachmentId()
		{
			return $this->attachment
				? $this->attachment->getId()
				: $this->attachmentId;
		}
		
		/**
		 * @return AttachmentImage
		**/
		public function setAttachment(Attachment $attachment)
		{
			$this->attachment = $attachment;
			$this->attachmentId = $attachment ? $attachment->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return AttachmentImage
		**/
		public function setAttachmentId($id)
		{
			$this->attachment = null;
			$this->attachmentId = $id;
			
			return $this;
		}
		
		/**
		 * @return AttachmentImage
		**/
		public function dropAttachment()
		{
			$this->attachment = null;
			$this->attachmentId = null;
			
			return $this;
		}
		
		public function getServer()
		{
			return $this->server;
		}
		
		/**
		 * @return AttachmentImage
		**/
		public function setServer($server)
		{
			$this->server = $server;
			
			return $this;
		}
		
		public function getFilename()
		{
			return $this->filename;
		}
		
		/**
		 * @return AttachmentImage
		**/
		public function setFilename($filename)
		{
			$this->filename = $filename;
			
			return $this;
		}
		
		public function getFileSize()
		{
			return $this->fileSize;
		}
		
		/**
		 * @return AttachmentImage
		**/
		public function setFileSize($fileSize)
		{
			$this->fileSize = $fileSize;
			
			return $this;
		}
		
		public function getWidth()
		{
			return $this->width;
		}
		
		/**
		 * @return AttachmentImage
		**/
		public function setWidth($width)
		{
			$this->width = $width;
			
			return $this;
		}
		
		public function getHeight()
		{
			return $this->height;
		}
		
		/**
		 * @return AttachmentImage
		**/
		public function setHeight($height)
		{
			$this->height = $height;
			
			return $this;
		}
	}
?>