<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-24 14:37:17                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPostReference extends IdentifiableObject
	{
		protected $referencedBy = null;
		protected $referencedById = null;
		protected $referencesTo = null;
		protected $referencesToId = null;
		
		/**
		 * @return Post
		**/
		public function getReferencedBy()
		{
			if (!$this->referencedBy && $this->referencedById) {
				$this->referencedBy = Post::dao()->getById($this->referencedById);
			}
			
			return $this->referencedBy;
		}
		
		public function getReferencedById()
		{
			return $this->referencedBy
				? $this->referencedBy->getId()
				: $this->referencedById;
		}
		
		/**
		 * @return PostReference
		**/
		public function setReferencedBy(Post $referencedBy)
		{
			$this->referencedBy = $referencedBy;
			$this->referencedById = $referencedBy ? $referencedBy->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PostReference
		**/
		public function setReferencedById($id)
		{
			$this->referencedBy = null;
			$this->referencedById = $id;
			
			return $this;
		}
		
		/**
		 * @return PostReference
		**/
		public function dropReferencedBy()
		{
			$this->referencedBy = null;
			$this->referencedById = null;
			
			return $this;
		}
		
		/**
		 * @return Post
		**/
		public function getReferencesTo()
		{
			if (!$this->referencesTo && $this->referencesToId) {
				$this->referencesTo = Post::dao()->getById($this->referencesToId);
			}
			
			return $this->referencesTo;
		}
		
		public function getReferencesToId()
		{
			return $this->referencesTo
				? $this->referencesTo->getId()
				: $this->referencesToId;
		}
		
		/**
		 * @return PostReference
		**/
		public function setReferencesTo(Post $referencesTo)
		{
			$this->referencesTo = $referencesTo;
			$this->referencesToId = $referencesTo ? $referencesTo->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PostReference
		**/
		public function setReferencesToId($id)
		{
			$this->referencesTo = null;
			$this->referencesToId = $id;
			
			return $this;
		}
		
		/**
		 * @return PostReference
		**/
		public function dropReferencesTo()
		{
			$this->referencesTo = null;
			$this->referencesToId = null;
			
			return $this;
		}
	}
?>