<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-05-02 20:12:17                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoBoardStatsDaily extends BoardStats
	{
		protected $date = null;
		
		/**
		 * @return Date
		**/
		public function getDate()
		{
			return $this->date;
		}
		
		/**
		 * @return BoardStatsDaily
		**/
		public function setDate(Date $date)
		{
			$this->date = $date;
			
			return $this;
		}
		
		/**
		 * @return BoardStatsDaily
		**/
		public function dropDate()
		{
			$this->date = null;
			
			return $this;
		}
	}
?>