<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-02-13 20:57:20                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModeratorLog_Message extends ModeratorLog
	{
		protected $message = null;
		
		public function getMessage()
		{
			return $this->message;
		}
		
		/**
		 * @return ModeratorLog_Message
		**/
		public function setMessage($message)
		{
			$this->message = $message;
			
			return $this;
		}
	}
?>