<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-05-02 20:12:17                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoBoardStatsHourly extends BoardStats
	{
		protected $hour = null;
		
		/**
		 * @return Timestamp
		**/
		public function getHour()
		{
			return $this->hour;
		}
		
		/**
		 * @return BoardStatsHourly
		**/
		public function setHour(Timestamp $hour)
		{
			$this->hour = $hour;
			
			return $this;
		}
		
		/**
		 * @return BoardStatsHourly
		**/
		public function dropHour()
		{
			$this->hour = null;
			
			return $this;
		}
	}
?>