<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-04-18 23:11:47                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoModeratorLog extends AutoProtoModeratorLog {

        public static function getDiscriminatorColumn() {
            return 'event_type_id';
        }

        public static function getDiscriminatorMap() {
            return ModeratorLogEventType::getClassMap();
        }
        
        public static function makeOnlyObject($className, $array, $prefix = null, ProtoDAO $parentDao = null) {

            if (isset($array[self::getDiscriminatorColumn()])) {
                $className = self::getDiscriminatorMap()[
                    $array[self::getDiscriminatorColumn()]
                ];
            }

            return parent::makeOnlyObject($className, $array, $prefix, $parentDao);
        }

    }
?>