<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-05-02 20:12:17                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoBoardStatsHourly extends AutoProtoBoardStatsHourly {/*_*/}
?>