<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-08-21 18:13:59                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoUserSession extends AutoProtoUserSession {/*_*/}
?>