<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-29 18:26:37                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoModeratorLog_Post extends AutoProtoModeratorLog_Post {/*_*/}
?>