<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-05-02 20:12:17                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	abstract class ProtoBoardStats extends AutoProtoBoardStats {
        public function getMetricProperties()
        {
            /** @var LightMetaProperty[] $list */
            $list = parent::getPropertyList();
            unset($list['id']);
            unset($list['board']);
            return $list;
        }
    }
?>