<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-04-16 15:41:40                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoUser extends AutoProtoUser {
        public function getPropertyReadableNames()
        {
            return [
                'showNsfw' => 'Показывать NSFW',
                'treeView' => 'Дерево постов',
                'viewDeleted' => 'Показ удаленных',
            ];
        }
    }