<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-02 15:25:45                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoAttachmentImage extends AutoProtoAttachmentImage {/*_*/}
?>