<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-07-12 18:02:36                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoModeratorLog_Message extends AutoProtoModeratorLog_Message {/*_*/}
?>