<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2018-01-04 15:17:04                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModeratorLog_AttachmentDAO extends ModeratorLog_PostDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'moderator_log';
		}
		
		public function getObjectName()
		{
			return 'ModeratorLog_Attachment';
		}
		
		public function getSequence()
		{
			return 'moderator_log_id';
		}
	}
?>