<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-02-18 21:56:09                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoBanDAO extends StorableDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'ban';
		}
		
		public function getObjectName()
		{
			return 'Ban';
		}
		
		public function getSequence()
		{
			return 'ban_id';
		}
	}
?>