<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-02-08 15:37:17                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModeratorLogDAO extends StorableDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'moderator_log';
		}
		
		public function getObjectName()
		{
			return 'ModeratorLog';
		}
		
		public function getSequence()
		{
			return 'moderator_log_id';
		}
	}
?>