<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-23 01:07:33                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoStorageTrashDAO extends StorableDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'storage_trash';
		}
		
		public function getObjectName()
		{
			return 'StorageTrash';
		}
		
		public function getSequence()
		{
			return 'storage_trash_id';
		}
	}
?>