<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-02 15:27:09                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAttachmentDAO extends StorableDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'attachment';
		}
		
		public function getObjectName()
		{
			return 'Attachment';
		}
		
		public function getSequence()
		{
			return 'attachment_id';
		}
	}
?>