<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-02-13 20:57:20                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModeratorLog_MessageDAO extends ModeratorLogDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'moderator_log';
		}
		
		public function getObjectName()
		{
			return 'ModeratorLog_Message';
		}
		
		public function getSequence()
		{
			return 'moderator_log_id';
		}
	}
?>