<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-24 14:37:17                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPostReferenceDAO extends StorableDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'post_reference';
		}
		
		public function getObjectName()
		{
			return 'PostReference';
		}
		
		public function getSequence()
		{
			return 'post_reference_id';
		}
	}
?>