<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-05-02 20:12:17                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoBoardStatsHourlyDAO extends BoardStatsDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'board_stats_hourly';
		}
		
		public function getObjectName()
		{
			return 'BoardStatsHourly';
		}
		
		public function getSequence()
		{
			return 'board_stats_hourly_id';
		}
	}
?>