<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-05-03 16:07:07                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoBoardStatsDailyDAO extends BoardStatsDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'board_stats_daily';
		}
		
		public function getObjectName()
		{
			return 'BoardStatsDaily';
		}
		
		public function getSequence()
		{
			return 'board_stats_daily_id';
		}
	}
?>