<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-02 15:25:45                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAttachmentImageDAO extends StorableDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'attachment_image';
		}
		
		public function getObjectName()
		{
			return 'AttachmentImage';
		}
		
		public function getSequence()
		{
			return 'attachment_image_id';
		}
	}
?>