<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-07-03 00:59:48                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class AttachmentImageRole extends EnumX
	{
		const ORIGINAL  = 1;
		const PX_50     = 50;
        const PX_100    = 100;
        const PX_200    = 200;
        const PX_400    = 400;
        const PX_600    = 600;

		protected static $names = array(
            self::ORIGINAL  => 'original',
            self::PX_50     => 'thumb_50px',
            self::PX_100    => 'thumb_100px',
            self::PX_200    => 'thumb_200px',
            self::PX_400    => 'thumb_400px',
            self::PX_600    => 'thumb_600px',
        );

        public function getMaxSize()
        {
            if ($this->id == self::ORIGINAL) {
                return null;
            }

            return $this->id;
		}
    }
?>