<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-02 15:25:45                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class AttachmentEmbed extends AutoAttachmentEmbed implements Prototyped, DAOConnected
	{
		/**
		 * @return AttachmentEmbed
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return AttachmentEmbedDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('AttachmentEmbedDAO');
		}
		
		/**
		 * @return ProtoAttachmentEmbed
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoAttachmentEmbed');
		}

        /**
         * @param $url
         * @return AttachmentEmbed|null
         */
        public static function createFromUrl($url)
        {
            foreach (AttachmentEmbedService::getList() as $service) {
                $embed = $service->match($url);
                if ($embed) {
                    return $embed;
                }
            }
            return null;
        }

        public function getEmbedHtml()
        {
            return $this->getService()->getHtml($this);
        }

        public function export()
        {
            return [
                'service' => $this->getService()->getName(),
                'embedId' => $this->getEmbedId(),
                'title' => $this->getTitle(),
                'html' => $this->getEmbedHtml(),
            ];
        }
	}
?>