<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-08-21 12:18:38                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class BoardModerator extends AutoBoardModerator implements Prototyped, DAOConnected
	{
		/**
		 * @return BoardModerator
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return BoardModeratorDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('BoardModeratorDAO');
		}
		
		/**
		 * @return ProtoBoardModerator
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoBoardModerator');
		}
		
		// your brilliant stuff goes here
	}
?>