<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-05-02 20:12:17                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class BoardStatsHourly extends AutoBoardStatsHourly implements Prototyped, DAOConnected
	{
		/**
		 * @return BoardStatsHourly
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return BoardStatsHourlyDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('BoardStatsHourlyDAO');
		}
		
		/**
		 * @return ProtoBoardStatsHourly
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoBoardStatsHourly');
		}

        public function getActualPeriodValue()
        {
            return $this->getHour();
        }

        public function setActualPeriodValue(Timestamp $timestamp)
        {
            return $this->setHour($timestamp);
        }

        protected function exportKey()
        {
            return $this->getHour()->toFormatString('Y-m-d Hч.');
        }


    }
?>