<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-04-07 17:00:39                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Dialog extends AutoDialog implements Prototyped, DAOConnected
	{
		/**
		 * @return Dialog
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return DialogDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('DialogDAO');
		}
		
		/**
		 * @return ProtoDialog
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoDialog');
		}

	}
?>