<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-04-07 17:00:39                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class DialogMessage extends AutoDialogMessage implements Prototyped, DAOConnected
	{
		/**
		 * @return DialogMessage
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return DialogMessageDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('DialogMessageDAO');
		}
		
		/**
		 * @return ProtoDialogMessage
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoDialogMessage');
		}

        public function getTextFormatted() {
            return Markdown::format($this->getText());
        }

        public function isIncomingFor(User $viewer)
        {
            return $this->getTo()->getUserId() == $viewer->getId();
        }

        public function isUnreadFor(User $viewer)
        {
            if (!$this->isIncomingFor($viewer)) return null;
            return !$this->isRead();
        }

        public function export(User $viewer) {
            return [
                'id'   => $this->getId(),
                'from' => $this->getFrom()->export(),
                'to'   => $this->getTo()->export(),
                'date' => $this->getDate()->toStamp(),
                'text' => $this->getText(),
                'html' => $this->getTextFormatted(),
                'isIncoming' => $this->isIncomingFor($viewer),
                'isUnread'   => $this->isUnreadFor($viewer),
            ];
        }
	}
?>