<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-08-29 14:44:36                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ImageFileFormat extends EnumX
	{
        const JPG = 1;
        const PNG = 2;
        const GIF = 3;

		protected static $names = array(
            self::JPG => 'JPG',
            self::PNG => 'PNG',
            self::GIF => 'GIF',
        );

        protected static $ext = array(
            self::JPG => 'jpg',
            self::PNG => 'png',
            self::GIF => 'gif',
        );

        protected static $mime = array(
            self::JPG => 'image/jpeg',
            self::PNG => 'image/png',
            self::GIF => 'image/gif',
        );

        public function getExtension() {
            return self::$ext[$this->id];
        }

        public static function jpg() { return new self(self::JPG); }
        public static function gif() { return new self(self::GIF); }
        public static function png() { return new self(self::PNG); }

        /**
         * @param $mimeType
         * @return ImageFileFormat|null
         */
        public static function createByMime($mimeType){
            $id = array_search($mimeType, self::$mime, true);
            return $id ? self::create($id) : null;
        }

        public function getMime() {
            return self::$mime[$this->id];
        }
	}
?>