<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-29 18:26:37                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModeratorLog_User extends AutoModeratorLog_User implements Prototyped, DAOConnected
	{
		/**
		 * @return ModeratorLog_User
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return ModeratorLog_UserDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('ModeratorLog_UserDAO');
		}
		
		/**
		 * @return ProtoModeratorLog_User
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModeratorLog_User');
		}

        public function exportInfo()
        {
            return [
                'user' => $this->getUser()->getLogin()
            ];
        }
	}
?>