<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-29 18:26:37                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModeratorLog_Ban extends AutoModeratorLog_Ban implements Prototyped, DAOConnected
	{
		/**
		 * @return ModeratorLog_Ban
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return ModeratorLog_BanDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('ModeratorLog_BanDAO');
		}
		
		/**
		 * @return ProtoModeratorLog_Ban
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModeratorLog_Ban');
		}

        public function exportInfo()
        {
            return [
                'ban' => $this->getBan()->export(true)
            ];
        }

    }
?>