<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-29 18:26:37                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModeratorLog_Property extends AutoModeratorLog_Property implements Prototyped, DAOConnected
	{
		/**
		 * @return ModeratorLog_Property
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return ModeratorLog_PropertyDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('ModeratorLog_PropertyDAO');
		}
		
		/**
		 * @return ProtoModeratorLog_Property
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModeratorLog_Property');
		}


        public function exportInfo()
        {
            return [
                'change' => [
                    'field' => $this->getPropertyName(),
                    'name'  => Board::proto()->getPropertyReadableName($this->getPropertyName()),
                    'old'   => $this->exportValue($this->getOldValue()),
                    'new'   => $this->exportValue($this->getNewValue()),
                ]
            ];
        }

        protected function exportValue($val) {
		    if ($val === 'true') {
		        return 'Да';
            }
            if ($val === 'false') {
		        return 'Нет';
            }
            if ($val === 'null' || $val === '') {
		        return '(нет)';
            }
            return $val;
        }

	}
?>