<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-04-18 23:11:47                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModeratorLogEventType extends EnumX
	{
        const BOARD_CREATED         = 1;
        const BOARD_CHANGED         = 2;
        const BOARD_OWNER_CHANGED   = 3;
        const MODERATOR_ADDED       = 20;
        const MODERATOR_REMOVED     = 21;
        const MOD_MESSAGE           = 22;
        const POST_DELETED          = 40;
        const POST_RESTORED         = 41;
        const THREAD_DELETED        = 42;
        const THREAD_RESTORED       = 43;
        const IMAGE_DELETED         = 44;
        const IMAGE_RESTORED        = 45;
        const USER_BANNED           = 60;
        const USER_UNBANNED         = 61;

		// implement me!
		protected static $names = array(
            self::BOARD_CREATED      => 'Доска создана',
            self::BOARD_CHANGED      => 'Доска изменена',
            self::BOARD_OWNER_CHANGED=> 'Доска передана',
            self::MODERATOR_ADDED    => 'Модератор добавлен',
            self::MODERATOR_REMOVED  => 'Модератор исключен',
            self::MOD_MESSAGE        => 'Сообщение для модераторов',
            self::POST_DELETED       => 'Пост удален',
            self::POST_RESTORED      => 'Пост восстановлен',
            self::THREAD_DELETED     => 'Тред удален',
            self::THREAD_RESTORED    => 'Тред восстановлен',
            self::IMAGE_DELETED      => 'Приложенный файл удален',
            self::IMAGE_RESTORED     => 'Приложенный файл восстановлен',
            self::USER_BANNED        => 'Бан выдан',
            self::USER_UNBANNED      => 'Бан снят',
        );

        protected static $classMap = [
            self::BOARD_CREATED         => ModeratorLog::class,
            self::BOARD_CHANGED         => ModeratorLog_Property::class,
            self::BOARD_OWNER_CHANGED   => ModeratorLog_User::class,
            self::MODERATOR_ADDED       => ModeratorLog_User::class,
            self::MODERATOR_REMOVED     => ModeratorLog_User::class,
            self::MOD_MESSAGE           => ModeratorLog_Message::class,
            self::POST_DELETED          => ModeratorLog_Post::class,
            self::POST_RESTORED         => ModeratorLog_Post::class,
            self::THREAD_DELETED        => ModeratorLog_Post::class,
            self::THREAD_RESTORED       => ModeratorLog_Post::class,
            self::IMAGE_DELETED         => ModeratorLog_Attachment::class,
            self::IMAGE_RESTORED        => ModeratorLog_Attachment::class,
            self::USER_BANNED           => ModeratorLog_Ban::class,
            self::USER_UNBANNED         => ModeratorLog_Ban::class,
        ];

        public static function getClassMap() {
            return self::$classMap;
        }

        public function getClassName()
        {
            return self::$classMap[$this->id];
        }
	}
?>