<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-24 14:37:17                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PostReference extends AutoPostReference implements Prototyped, DAOConnected
	{
		/**
		 * @return PostReference
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PostReferenceDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PostReferenceDAO');
		}
		
		/**
		 * @return ProtoPostReference
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPostReference');
		}
		
		// your brilliant stuff goes here
	}
?>