<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-03-23 01:07:33                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class StorageTrash extends AutoStorageTrash implements Prototyped, DAOConnected
	{
		/**
		 * @return StorageTrash
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return StorageTrashDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('StorageTrashDAO');
		}
		
		/**
		 * @return ProtoStorageTrash
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoStorageTrash');
		}
		
		// your brilliant stuff goes here
	}
?>