<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-22 19:24:29                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class UserIdentity extends AutoUserIdentity implements Prototyped, DAOConnected
	{
		/**
		 * @return UserIdentity
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return UserIdentityDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('UserIdentityDAO');
		}
		
		/**
		 * @return ProtoUserIdentity
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoUserIdentity');
		}

        /**
         * @return string
         */
        public static function makeAddress() {
            $address = '0x';
            for ($octets = 0; $octets < 4; $octets++) {
                $address .= sprintf('%02x', mt_rand(0x00, 0xff));
            }
            return $address;
        }

        /**
         * @return array
         */
        public function export()
        {
            return [
                'address'   => $this->getAddress(),
                'name'      => $this->getName(),
            ];
        }
	}
?>