<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-04-16 15:41:40                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class UserRole extends EnumX
	{
		const USER 		= 1;
		const MODERATOR = 2;
		const ADMIN 	= 7;

		protected static $names = array(
			self::USER 		=> 'Пользователь',
			self::MODERATOR => 'Модератор',
			self::ADMIN		=> 'Администратор',
		);

		/**
		 * @param int $id
		 * @return UserRole
		 */
		public static function create($id) {
			return new self($id);
		}

        public function isGlobalMod()
        {
            return $this->is(self::MODERATOR)
                || $this->is(self::ADMIN);
		}

        public function isGlobalAdmin()
        {
            return $this->is(self::ADMIN);
		}
	}
